<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $languages = array(
            array('id' => '2', 'lang' => 'Abkhazian', 'native' => 'Abkhazian', 'iso_code' => 'ab', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '3', 'lang' => 'Afar', 'native' => 'Afar', 'iso_code' => 'aa', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '4', 'lang' => 'Afrikaans', 'native' => 'Afrikaans', 'iso_code' => 'af', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '5', 'lang' => 'Akan', 'native' => 'Akan', 'iso_code' => 'ak', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '6', 'lang' => 'Albanian', 'native' => 'Albanian', 'iso_code' => 'sq', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '7', 'lang' => 'Amharic', 'native' => 'Amharic', 'iso_code' => 'am', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '8', 'lang' => 'Arabic', 'native' => 'عربى', 'iso_code' => 'ar', 'is_active' => '1', 'is_rtl' => '1', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '9', 'lang' => 'Aragonese', 'native' => 'Aragonese', 'iso_code' => 'an', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '10', 'lang' => 'Armenian', 'native' => 'Armenian', 'iso_code' => 'hy', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '11', 'lang' => 'Assamese', 'native' => 'Assamese', 'iso_code' => 'as', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '12', 'lang' => 'Avaric', 'native' => 'Avaric', 'iso_code' => 'av', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '13', 'lang' => 'Avestan', 'native' => 'Avestan', 'iso_code' => 'ae', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '14', 'lang' => 'Aymara', 'native' => 'Aymara', 'iso_code' => 'ay', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '15', 'lang' => 'Azerbaijani', 'native' => 'Azerbaijani', 'iso_code' => 'az', 'is_active' => '0', 'is_rtl' => '1', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '16', 'lang' => 'Bambara', 'native' => 'Bambara', 'iso_code' => 'bm', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '17', 'lang' => 'Bashkir', 'native' => 'Bashkir', 'iso_code' => 'ba', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '18', 'lang' => 'Basque', 'native' => 'Basque', 'iso_code' => 'eu', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '19', 'lang' => 'Belarusian', 'native' => 'Belarusian', 'iso_code' => 'be', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '20', 'lang' => 'Bengali (Bangla)', 'native' => 'Bengali (Bangla)', 'iso_code' => 'bn', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '21', 'lang' => 'Bihari', 'native' => 'Bihari', 'iso_code' => 'bh', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '22', 'lang' => 'Bislama', 'native' => 'Bislama', 'iso_code' => 'bi', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '23', 'lang' => 'Bosnian', 'native' => 'Bosnian', 'iso_code' => 'bs', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '24', 'lang' => 'Breton', 'native' => 'Breton', 'iso_code' => 'br', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '25', 'lang' => 'Bulgarian', 'native' => 'Bulgarian', 'iso_code' => 'bg', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '26', 'lang' => 'Burmese', 'native' => 'Burmese', 'iso_code' => 'my', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '27', 'lang' => 'Catalan', 'native' => 'Catalan', 'iso_code' => 'ca', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '28', 'lang' => 'Chamorro', 'native' => 'Chamorro', 'iso_code' => 'ch', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '29', 'lang' => 'Chechen', 'native' => 'Chechen', 'iso_code' => 'ce', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '30', 'lang' => 'Chichewa, Chewa, Nyanja', 'native' => 'Chichewa, Chewa, Nyanja', 'iso_code' => 'ny', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '31', 'lang' => 'Chinese', 'native' => 'Chinese', 'iso_code' => 'zh', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '32', 'lang' => 'Chinese (Simplified)', 'native' => 'Chinese (Simplified)', 'iso_code' => 'zh-Hans', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '33', 'lang' => 'Chinese (Traditional)', 'native' => 'Chinese (Traditional)', 'iso_code' => 'zh-Hant', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '34', 'lang' => 'Chuvash', 'native' => 'Chuvash', 'iso_code' => 'cv', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '35', 'lang' => 'Cornish', 'native' => 'Cornish', 'iso_code' => 'kw', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '36', 'lang' => 'Corsican', 'native' => 'Corsican', 'iso_code' => 'co', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '37', 'lang' => 'Cree', 'native' => 'Cree', 'iso_code' => 'cr', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '38', 'lang' => 'Croatian', 'native' => 'Croatian', 'iso_code' => 'hr', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '39', 'lang' => 'Czech', 'native' => 'Czech', 'iso_code' => 'cs', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '40', 'lang' => 'Danish', 'native' => 'Danish', 'iso_code' => 'da', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '41', 'lang' => 'Divehi, Dhivehi, Maldivian', 'native' => 'Divehi, Dhivehi, Maldivian', 'iso_code' => 'dv', 'is_active' => '0', 'is_rtl' => '1', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '42', 'lang' => 'Dutch', 'native' => 'Dutch', 'iso_code' => 'nl', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '43', 'lang' => 'Dzongkha', 'native' => 'Dzongkha', 'iso_code' => 'dz', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '44', 'lang' => 'English', 'native' => 'English', 'iso_code' => 'en', 'is_active' => '1', 'is_rtl' => '0', 'is_default' => '1', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => '2020-10-24 15:48:45'),
            array('id' => '45', 'lang' => 'Esperanto', 'native' => 'Esperanto', 'iso_code' => 'eo', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '46', 'lang' => 'Estonian', 'native' => 'Estonian', 'iso_code' => 'et', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '47', 'lang' => 'Ewe', 'native' => 'Ewe', 'iso_code' => 'ee', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '48', 'lang' => 'Faroese', 'native' => 'Faroese', 'iso_code' => 'fo', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '49', 'lang' => 'Fijian', 'native' => 'Fijian', 'iso_code' => 'fj', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '50', 'lang' => 'Finnish', 'native' => 'Finnish', 'iso_code' => 'fi', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '51', 'lang' => 'French', 'native' => 'French', 'iso_code' => 'fr', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '52', 'lang' => 'Fula, Fulah, Pulaar, Pular', 'native' => 'Fula, Fulah, Pulaar, Pular', 'iso_code' => 'ff', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '53', 'lang' => 'Galician', 'native' => 'Galician', 'iso_code' => 'gl', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '54', 'lang' => 'Gaelic (Scottish)', 'native' => 'Gaelic (Scottish)', 'iso_code' => 'gd', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '55', 'lang' => 'Gaelic (Manx)', 'native' => 'Gaelic (Manx)', 'iso_code' => 'gv', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '56', 'lang' => 'Georgian', 'native' => 'Georgian', 'iso_code' => 'ka', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '57', 'lang' => 'German', 'native' => 'German', 'iso_code' => 'de', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '58', 'lang' => 'Greek', 'native' => 'Greek', 'iso_code' => 'el', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '59', 'lang' => 'Greenlandic', 'native' => 'Greenlandic', 'iso_code' => 'kl', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '60', 'lang' => 'Guarani', 'native' => 'Guarani', 'iso_code' => 'gn', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '61', 'lang' => 'Gujarati', 'native' => 'Gujarati', 'iso_code' => 'gu', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '62', 'lang' => 'Haitian Creole', 'native' => 'Haitian Creole', 'iso_code' => 'ht', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '63', 'lang' => 'Hausa', 'native' => 'Hausa', 'iso_code' => 'ha', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '64', 'lang' => 'Hebrew', 'native' => 'Hebrew', 'iso_code' => 'he', 'is_active' => '0', 'is_rtl' => '1', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '65', 'lang' => 'Herero', 'native' => 'Herero', 'iso_code' => 'hz', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '66', 'lang' => 'Hindi', 'native' => 'Hindi', 'iso_code' => 'hi', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '67', 'lang' => 'Hiri Motu', 'native' => 'Hiri Motu', 'iso_code' => 'ho', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '68', 'lang' => 'Hungarian', 'native' => 'Hungarian', 'iso_code' => 'hu', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '69', 'lang' => 'Icelandic', 'native' => 'Icelandic', 'iso_code' => 'is', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '70', 'lang' => 'Ido', 'native' => 'Ido', 'iso_code' => 'io', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '71', 'lang' => 'Igbo', 'native' => 'Igbo', 'iso_code' => 'ig', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '72', 'lang' => 'Indonesian', 'native' => 'Indonesian', 'iso_code' => 'id, in', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '73', 'lang' => 'Interlingua', 'native' => 'Interlingua', 'iso_code' => 'ia', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '74', 'lang' => 'Interlingue', 'native' => 'Interlingue', 'iso_code' => 'ie', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '75', 'lang' => 'Inuktitut', 'native' => 'Inuktitut', 'iso_code' => 'iu', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '76', 'lang' => 'Inupiak', 'native' => 'Inupiak', 'iso_code' => 'ik', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '77', 'lang' => 'Irish', 'native' => 'Irish', 'iso_code' => 'ga', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '78', 'lang' => 'Italian', 'native' => 'Italian', 'iso_code' => 'it', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '79', 'lang' => 'Japanese', 'native' => 'Japanese', 'iso_code' => 'ja', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '80', 'lang' => 'Javanese', 'native' => 'Javanese', 'iso_code' => 'jv', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '81', 'lang' => 'Kalaallisut, Greenlandic', 'native' => 'Kalaallisut, Greenlandic', 'iso_code' => 'kl', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '82', 'lang' => 'Kannada', 'native' => 'Kannada', 'iso_code' => 'kn', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '83', 'lang' => 'Kanuri', 'native' => 'Kanuri', 'iso_code' => 'kr', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '84', 'lang' => 'Kashmiri', 'native' => 'Kashmiri', 'iso_code' => 'ks', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '85', 'lang' => 'Kazakh', 'native' => 'Kazakh', 'iso_code' => 'kk', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '86', 'lang' => 'Khmer', 'native' => 'Khmer', 'iso_code' => 'km', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '87', 'lang' => 'Kikuyu', 'native' => 'Kikuyu', 'iso_code' => 'ki', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '88', 'lang' => 'Kinyarwanda (Rwanda)', 'native' => 'Kinyarwanda (Rwanda)', 'iso_code' => 'rw', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '89', 'lang' => 'Kirundi', 'native' => 'Kirundi', 'iso_code' => 'rn', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '90', 'lang' => 'Kyrgyz', 'native' => 'Kyrgyz', 'iso_code' => 'ky', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '91', 'lang' => 'Komi', 'native' => 'Komi', 'iso_code' => 'kv', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '92', 'lang' => 'Kongo', 'native' => 'Kongo', 'iso_code' => 'kg', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '93', 'lang' => 'Korean', 'native' => 'Korean', 'iso_code' => 'ko', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '94', 'lang' => 'Kurdish', 'native' => 'Kurdish', 'iso_code' => 'ku', 'is_active' => '0', 'is_rtl' => '1', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '95', 'lang' => 'Kwanyama', 'native' => 'Kwanyama', 'iso_code' => 'kj', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '96', 'lang' => 'Lao', 'native' => 'Lao', 'iso_code' => 'lo', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '97', 'lang' => 'Latin', 'native' => 'Latin', 'iso_code' => 'la', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '98', 'lang' => 'Latvian (Lettish)', 'native' => 'Latvian (Lettish)', 'iso_code' => 'lv', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '99', 'lang' => 'Limburgish ( Limburger)', 'native' => 'Limburgish ( Limburger)', 'iso_code' => 'li', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '100', 'lang' => 'Lingala', 'native' => 'Lingala', 'iso_code' => 'ln', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '101', 'lang' => 'Lithuanian', 'native' => 'Lithuanian', 'iso_code' => 'lt', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '102', 'lang' => 'Luga-Katanga', 'native' => 'Luga-Katanga', 'iso_code' => 'lu', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '103', 'lang' => 'Luganda, Ganda', 'native' => 'Luganda, Ganda', 'iso_code' => 'lg', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '104', 'lang' => 'Luxembourgish', 'native' => 'Luxembourgish', 'iso_code' => 'lb', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '105', 'lang' => 'Manx', 'native' => 'Manx', 'iso_code' => 'gv', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '106', 'lang' => 'Macedonian', 'native' => 'Macedonian', 'iso_code' => 'mk', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '107', 'lang' => 'Malagasy', 'native' => 'Malagasy', 'iso_code' => 'mg', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '108', 'lang' => 'Malay', 'native' => 'Malay', 'iso_code' => 'ms', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '109', 'lang' => 'Malayalam', 'native' => 'Malayalam', 'iso_code' => 'ml', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '110', 'lang' => 'Maltese', 'native' => 'Maltese', 'iso_code' => 'mt', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '111', 'lang' => 'Maori', 'native' => 'Maori', 'iso_code' => 'mi', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '112', 'lang' => 'Marathi', 'native' => 'Marathi', 'iso_code' => 'mr', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '113', 'lang' => 'Marshallese', 'native' => 'Marshallese', 'iso_code' => 'mh', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '114', 'lang' => 'Moldavian', 'native' => 'Moldavian', 'iso_code' => 'mo', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '115', 'lang' => 'Mongolian', 'native' => 'Mongolian', 'iso_code' => 'mn', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '116', 'lang' => 'Nauru', 'native' => 'Nauru', 'iso_code' => 'na', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '117', 'lang' => 'Navajo', 'native' => 'Navajo', 'iso_code' => 'nv', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '118', 'lang' => 'Ndonga', 'native' => 'Ndonga', 'iso_code' => 'ng', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '119', 'lang' => 'Northern Ndebele', 'native' => 'Northern Ndebele', 'iso_code' => 'nd', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '120', 'lang' => 'Nepali', 'native' => 'Nepali', 'iso_code' => 'ne', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '121', 'lang' => 'Norwegian', 'native' => 'Norwegian', 'iso_code' => 'no', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '122', 'lang' => 'Norwegian bokmål', 'native' => 'Norwegian bokm?l', 'iso_code' => 'nb', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '123', 'lang' => 'Norwegian nynorsk', 'native' => 'Norwegian nynorsk', 'iso_code' => 'nn', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '124', 'lang' => 'Nuosu', 'native' => 'Nuosu', 'iso_code' => 'ii', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '125', 'lang' => 'Occitan', 'native' => 'Occitan', 'iso_code' => 'oc', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '126', 'lang' => 'Ojibwe', 'native' => 'Ojibwe', 'iso_code' => 'oj', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '127', 'lang' => 'Old Church Slavonic, Old Bulgarian', 'native' => 'Old Church Slavonic, Old Bulgarian', 'iso_code' => 'cu', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '128', 'lang' => 'Oriya', 'native' => 'Oriya', 'iso_code' => 'or', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '129', 'lang' => 'Oromo (Afaan Oromo)', 'native' => 'Oromo (Afaan Oromo)', 'iso_code' => 'om', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '130', 'lang' => 'Ossetian', 'native' => 'Ossetian', 'iso_code' => 'os', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '131', 'lang' => 'P?li', 'native' => 'P?li', 'iso_code' => 'pi', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '132', 'lang' => 'Pashto, Pushto', 'native' => 'Pashto, Pushto', 'iso_code' => 'ps', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '133', 'lang' => 'Persian (Farsi)', 'native' => 'Persian (Farsi)', 'iso_code' => 'fa', 'is_active' => '0', 'is_rtl' => '1', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '134', 'lang' => 'Polish', 'native' => 'Polish', 'iso_code' => 'pl', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '135', 'lang' => 'Portuguese', 'native' => 'Portuguese', 'iso_code' => 'pt', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '136', 'lang' => 'Punjabi (Eastern)', 'native' => 'Punjabi (Eastern)', 'iso_code' => 'pa', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '137', 'lang' => 'Quechua', 'native' => 'Quechua', 'iso_code' => 'qu', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '138', 'lang' => 'Romansh', 'native' => 'Romansh', 'iso_code' => 'rm', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '139', 'lang' => 'Romanian', 'native' => 'Romanian', 'iso_code' => 'ro', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '140', 'lang' => 'Russian', 'native' => 'Russian', 'iso_code' => 'ru', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '141', 'lang' => 'Sami', 'native' => 'Sami', 'iso_code' => 'se', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '142', 'lang' => 'Samoan', 'native' => 'Samoan', 'iso_code' => 'sm', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '143', 'lang' => 'Sango', 'native' => 'Sango', 'iso_code' => 'sg', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '144', 'lang' => 'Sanskrit', 'native' => 'Sanskrit', 'iso_code' => 'sa', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '145', 'lang' => 'Serbian', 'native' => 'Serbian', 'iso_code' => 'sr', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '146', 'lang' => 'Serbo-Croatian', 'native' => 'Serbo-Croatian', 'iso_code' => 'sh', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '147', 'lang' => 'Sesotho', 'native' => 'Sesotho', 'iso_code' => 'st', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '148', 'lang' => 'Setswana', 'native' => 'Setswana', 'iso_code' => 'tn', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '149', 'lang' => 'Shona', 'native' => 'Shona', 'iso_code' => 'sn', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '150', 'lang' => 'Sichuan Yi', 'native' => 'Sichuan Yi', 'iso_code' => 'ii', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '151', 'lang' => 'Sindhi', 'native' => 'Sindhi', 'iso_code' => 'sd', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '152', 'lang' => 'Sinhalese', 'native' => 'Sinhalese', 'iso_code' => 'si', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '153', 'lang' => 'Siswati', 'native' => 'Siswati', 'iso_code' => 'ss', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '154', 'lang' => 'Slovak', 'native' => 'Slovak', 'iso_code' => 'sk', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '155', 'lang' => 'Slovenian', 'native' => 'Slovenian', 'iso_code' => 'sl', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '156', 'lang' => 'Somali', 'native' => 'Somali', 'iso_code' => 'so', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '157', 'lang' => 'Southern Ndebele', 'native' => 'Southern Ndebele', 'iso_code' => 'nr', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '158', 'lang' => 'Spanish', 'native' => 'Español', 'iso_code' => 'es', 'is_active' => '1', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => '2020-10-24 15:48:45'),
            array('id' => '159', 'lang' => 'Sundanese', 'native' => 'Sundanese', 'iso_code' => 'su', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '160', 'lang' => 'Swahili (Kiswahili)', 'native' => 'Swahili (Kiswahili)', 'iso_code' => 'sw', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '161', 'lang' => 'Swati', 'native' => 'Swati', 'iso_code' => 'ss', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '162', 'lang' => 'Swedish', 'native' => 'Swedish', 'iso_code' => 'sv', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '163', 'lang' => 'Tagalog', 'native' => 'Tagalog', 'iso_code' => 'tl', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '164', 'lang' => 'Tahitian', 'native' => 'Tahitian', 'iso_code' => 'ty', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '165', 'lang' => 'Tajik', 'native' => 'Tajik', 'iso_code' => 'tg', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '166', 'lang' => 'Tamil', 'native' => 'Tamil', 'iso_code' => 'ta', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '167', 'lang' => 'Tatar', 'native' => 'Tatar', 'iso_code' => 'tt', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '168', 'lang' => 'Telugu', 'native' => 'Telugu', 'iso_code' => 'te', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '169', 'lang' => 'Thai', 'native' => 'Thai', 'iso_code' => 'th', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '170', 'lang' => 'Tibetan', 'native' => 'Tibetan', 'iso_code' => 'bo', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '171', 'lang' => 'Tigrinya', 'native' => 'Tigrinya', 'iso_code' => 'ti', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '172', 'lang' => 'Tonga', 'native' => 'Tonga', 'iso_code' => 'to', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '173', 'lang' => 'Tsonga', 'native' => 'Tsonga', 'iso_code' => 'ts', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '174', 'lang' => 'Turkish', 'native' => 'Turkish', 'iso_code' => 'tr', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '175', 'lang' => 'Turkmen', 'native' => 'Turkmen', 'iso_code' => 'tk', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '176', 'lang' => 'Twi', 'native' => 'Twi', 'iso_code' => 'tw', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '177', 'lang' => 'Uyghur', 'native' => 'Uyghur', 'iso_code' => 'ug', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '178', 'lang' => 'Ukrainian', 'native' => 'Ukrainian', 'iso_code' => 'uk', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '179', 'lang' => 'Urdu', 'native' => 'اردو', 'iso_code' => 'ur', 'is_active' => '1', 'is_rtl' => '1', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '180', 'lang' => 'Uzbek', 'native' => 'Uzbek', 'iso_code' => 'uz', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '181', 'lang' => 'Venda', 'native' => 'Venda', 'iso_code' => 've', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '182', 'lang' => 'Vietnamese', 'native' => 'Vietnamese', 'iso_code' => 'vi', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '183', 'lang' => 'Volapük', 'native' => 'Volap?k', 'iso_code' => 'vo', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '184', 'lang' => 'Wallon', 'native' => 'Wallon', 'iso_code' => 'wa', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '185', 'lang' => 'Welsh', 'native' => 'Welsh', 'iso_code' => 'cy', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '186', 'lang' => 'Wolof', 'native' => 'Wolof', 'iso_code' => 'wo', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '187', 'lang' => 'Western Frisian', 'native' => 'Western Frisian', 'iso_code' => 'fy', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '188', 'lang' => 'Xhosa', 'native' => 'Xhosa', 'iso_code' => 'xh', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '189', 'lang' => 'Yiddish', 'native' => 'Yiddish', 'iso_code' => 'yi, ji', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '190', 'lang' => 'Yoruba', 'native' => 'Yoruba', 'iso_code' => 'yo', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '191', 'lang' => 'Zhuang, Chuang', 'native' => 'Zhuang, Chuang', 'iso_code' => 'za', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL),
            array('id' => '192', 'lang' => 'Zulu', 'native' => 'Zulu', 'iso_code' => 'zu', 'is_active' => '0', 'is_rtl' => '0', 'is_default' => '0', 'created_at' => '2018-06-25 04:16:38', 'updated_at' => NULL)
        );


        DB::table('languages')->insert($languages);
    }
}
